language: ruby
rvm: 2.4
cache: bundler
install: bundle install
script: bundle exec rake site:deploy --quiet
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master # Or `gh-pages`
