version: "3"
services:
  site:
    container_name: jekyll
    command: jekyll serve --watch --incremental --force_polling
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
     - 4000:4000